facebook.com
login.facebook.com
www.login.facebook.com
fbcdn.net
www.fbcdn.net
fbcdn.com
www.fbcdn.com
static.ak.fbcdn.net
static.ak.connect.facebook.com
connect.facebook.net
www.connect.facebook.net
apps.facebook.com
